config/routes.rb
BlackLotus::Application.routes.draw do

  resources :cards
  get 'cards/:id/fetch_info' => 'cards#fetch_info', :as => :card_fetch_info

  resources :decks
  get 'decks/:id/build'       => 'decks#build',      :as => :build_deck
  post 'decks/:id/build_save' => 'decks#build_save', :as => :save_build_deck
  get 'decks/:id/print'       => 'decks#print',      :as => :deck_print

  resources :editions

  # Utility routes
  get 'utilities/(index)' => 'utilities#index', 
    :as => :utilities
  get 'utilities/export_cards' => 'utilities#export_cards', 
    :as => :utils_export_cards
  get 'utilities/sync_db' => 'utilities#sync_db', 
    :as => :utils_sync_db

  root :to => 'home#index'

end

app/models/edition.rb
class Edition < ActiveRecord::Base
  paginates_per 10

  validates_presence_of :name, :code_name, :release_date, :card_count
  validates_numericality_of :card_count, 
    :only_integer => true, :greater_than => 0

  attr_accessible :card_count, :code_name, :name, :online_code, :release_date
  has_and_belongs_to_many :cards, -> {order :name}
  ##############################################################################
  def self.recent_editions
    yrs_ago = Time.now - 2.year
    re = Edition
      .where("release_date between :yrs_ago and :now", {yrs_ago: yrs_ago, now: Time.now})
      .order('release_date')

    return re
  end

end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  # GET /editions
  # GET /editions.json
  def index
    @editions = Edition.where("name like '%#{params[:search_string]}%'")
                       .order(:release_date)
                       .page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @editions }
    end
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
    @edition = Edition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/new
  # GET /editions/new.json
  def new
    @edition = Edition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/1/edit
  def edit
    @edition = Edition.find(params[:id])
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = Edition.new(params[:edition])

    respond_to do |format|
      if @edition.save
        format.html { redirect_to @edition, notice: 'Edition was successfully created.' }
        format.json { render json: @edition, status: :created, location: @edition }
      else
        format.html { render action: "new" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /editions/1
  # PUT /editions/1.json
  def update
    @edition = Edition.find(params[:id])

    respond_to do |format|
      if @edition.update_attributes(params[:edition])
        format.html { redirect_to @edition, notice: 'Edition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition = Edition.find(params[:id])
    @edition.destroy

    respond_to do |format|
      format.html { redirect_to editions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/editions_helper.rb
module EditionsHelper

  def edition_error?(attr)
    return @edition.errors[attr].present?
  end

  def display_edition_error(attr)
    display_error_if_error @edition, attr
  end

end

app/views/editions/_form.html.erb
<%= form_for @edition, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @edition.errors.any? %>
    <div class="alert alert-danger">
      <h4>Unable to save Edition: <%= @edition.errors.count %> errors.</h4>
    </div>
  <% end %>

  <div class="form-group <%= edition_error?(:name) ? 'has-error' : '' %>">
    <%= f.label :name, :class=> "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, :autofocus => true, :class => 'form-control' %>
      <%= display_edition_error :name %>
    </div>
  </div>

  <div class="form-group <%= edition_error?(:code_name) ? 'has-error' : '' %>">
    <%= f.label :code_name, :class=> "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :code_name, :class => 'form-control' %>
      <%= display_edition_error :code_name %>
    </div>
  </div>

  <div class="form-group <%= edition_error?(:online_code) ? 'has-error' : '' %>">
    <%= f.label :online_code, :class=> "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :online_code, :class => 'form-control' %>
      <%= display_edition_error :online_code %>
    </div>
  </div>

  <div class="form-group <%= edition_error?(:card_count) ? 'has-error' : '' %>">
    <%= f.label :card_count, :class=> "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :card_count, :class => 'form-control' %>
      <%= display_edition_error :card_count %>
    </div>
  </div>

  <div class="form-group <%= edition_error?(:release_date) ? 'has-error' : '' %>">
    <%= f.label :release_date, :class=> "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <div class="input-group date" id="release_date" data-date="<% Date.today.to_s %>" data-date-format="yyyy-mm-dd">
        <%= f.text_field :release_date, :class => 'form-control' %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
      </div>
      <%= display_edition_error :release_date %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
      <%= f.submit nil, :class => "btn btn-primary" %>
      <%= link_to 'Back', :back, :class => "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/editions/edit.html.erb
<div class="page-header"><h1>Edit Edition</h1></div>

<%= render 'form' %>

app/views/editions/index.html.erb
<div class="page-header"><h1>Editions</h1></div>

<%= paginate @editions %>

<form>
  <div class="form-group">
    <div class="input-group">
      <input type="text" name="search_string" class="input form-control" autofocus>
      <i class="input-group-addon glyphicon glyphicon-search"></i>
    </div>
  </div>
</form>

<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Symbol</th>
    <th>Released</th>
    <th>Cards</th>
    <th>Progress</th>
    <th></th>
  </tr>

<% @editions.each do |edition| %>
  <tr>
    <td class="col-md-3"><%= link_to edition.name, edition %></td>
    <td><%= image_tag "editions/#{edition.code_name}.gif" %></td>
    <td><%= edition.release_date %></td>
    <td>
      <%= edition.cards.count %>/<%= edition.card_count %>
    </td>
    <td>
      <% percent = ((edition.cards.count.to_f/edition.card_count) * 100).to_i %>
      <div title="<%= percent %>%" class="progress progress-striped">
        <div class="progress-bar" style="width: <%= percent %>%;"></div>
      </div>
    </td>
    <td>
      <%= link_to edition, :class => "btn btn-default btn-sm" do %>
        <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
      <%= link_to edit_edition_path(edition), :class => "btn btn-default btn-sm"  do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
      <%= link_to edition, :class => "btn btn-sm btn-danger", method: :delete, data: { confirm: "Delete '#{edition.name}'?" } do %>
        <i class="glyphicon glyphicon-trash  "></i>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Edition', new_edition_path, :class => "btn btn-primary" %>

app/views/editions/new.html.erb
<div class="page-header"><h1>New Edition</h1></div>

<%= render 'form' %>

app/views/editions/show.html.erb
<div class="page-header">
  <h1><%= @edition.name %> (<%= @edition.cards.count %>/<%= @edition.card_count %>)</h1>
  <%= link_to 'Edit', edit_edition_path(@edition), :class => "btn btn-primary btn-xs" %>
  <%= link_to 'Back', :back, :class => "btn btn-default btn-xs" %>
</div>

<div class="row">
  <% @edition.cards.each do |card| %>
  <div class="col-xs-4 col-md-2 col-lg-2">
    <div class="thumbnail">
        <a href="<%= card_path card%>"><img src="<%= card_image_path(card, @edition) %>" class="img-responsive"></a>
    </div>
  </div>
  <% end %>
</div>