config/routes.rb
BlackLotus::Application.routes.draw do

  resources :cards
  get 'cards/:id/fetch_info' => 'cards#fetch_info', :as => :card_fetch_info

  resources :decks
  get 'decks/:id/build'       => 'decks#build',      :as => :build_deck
  post 'decks/:id/build_save' => 'decks#build_save', :as => :save_build_deck
  get 'decks/:id/print'       => 'decks#print',      :as => :deck_print

  resources :editions

  # Utility routes
  get 'utilities/(index)' => 'utilities#index', 
    :as => :utilities
  get 'utilities/export_cards' => 'utilities#export_cards', 
    :as => :utils_export_cards
  get 'utilities/sync_db' => 'utilities#sync_db', 
    :as => :utils_sync_db

  root :to => 'home#index'

end

app/models/card.rb
class Card < ActiveRecord::Base

  LOWER_WORDS = {
    the:  true,
    in:   true,
    of:   true,
    a:    true,
    to:   true,
    by:   true,
    for:  true,
    from: true,
    at:   true
  }

  CARD_TYPES = {
    land:                 'Land',
    basic_land:           'Basic Land',
    basic_snow_land:      'Basic Snow Land',
    legendary_snow_land:  'Legendary Snow Land',
    creature:             'Creature',
    elite_creature:       'Elite Creature',
    artifact_creature:    'Artifact Creature',
    enchantment_creature: 'Enchantment Creature',
    legendary_creature:   'Legendary Creature',
    legendary_enchantment_artifact: 'Legendary Enchantment Artifact',
    legendary_enchantment_creature: 'Legendary Enchantment Creature',
    snow_creature:        'Snow Creature',
    instant:              'Instant',
    tribal_instant:       'Tribal Instant',
    sorcery:              'Sorcery',
    tribal_sorcery:       'Tribal Sorcery',
    artifact:             'Artifact',
    snow_artifact:        'Snow Artifact',
    legendary_artifact:   'Legendary Artifact',
    enchantment:          'Enchantment',
    tribal_enchantment:   'Tribal Enchantment',
    planeswalker:         'Planeswalker',
    scheme:               'Scheme'
  }

  COLORS = {
    red:       { name: 'Red',       code: 'R' },
    green:     { name: 'Green',     code: 'G' },
    blue:      { name: 'Blue',      code: 'U' },
    black:     { name: 'Black',     code: 'B' },
    white:     { name: 'White',     code: 'W' },
    colorless: { name: 'Colorless', code: 'C' },
    none:      { name: 'None',      code: '-' },

    # Nothing should be entered with this value. This is here purely to assist
    # in card searches. See cards_controller.rb, line 19(ish)
    generic:   { name: 'Generic',   code: '*' }
  }

  RARITIES = [
    'Common',
    'Uncommon',
    'Rare',
    'Mythic Rare'
  ]

  validates_presence_of :name, :editions
  validates_presence_of :mana_cost,
    :unless => Proc.new {|card| card.main_type =~ /Land$/ }
  validates_numericality_of :count, :only_integer => true, :greater_than => 0
  validates_format_of :mana_cost,
    :with => /\AX*(\d+)?({[RGUBWC]\/[RGUBWC]}|[RGUBWC\-])*\z/
  validates_inclusion_of :main_type, :in => CARD_TYPES.values,
    :message => "'%{value}' is not a valid main type"
  validates_inclusion_of :rarity, :in => RARITIES,
    :message => "'%{value}' is not a valid rarity"

  before_validation :fixup_data

  attr_accessible :count, :foil, :image_name, :main_type, :mana_cost, :name,
                  :rarity, :sub_type, :text_box

  has_and_belongs_to_many :editions, -> {order :release_date}

  has_many :card_in_deck, :dependent => :destroy
  has_many :decks, :through => :card_in_deck
  ##############################################################################
  def gen_image_name
      iname = self.name.downcase
      iname.gsub!(/\s/, '_')
      iname.gsub!(/[^A-Za-z0-9\-_]/, '')

      self.image_name = iname + ".jpg"
  end
  ##############################################################################
  def image_path(edition = nil)
    edition = latest_edition if edition.nil?

    img_name = File.basename(image_name, '.jpg')
    img_name += '-' + edition.code_name.downcase + '.jpg'

    return("/card_images/#{img_name}")
  end
  ##############################################################################
  def available_editions
    all_editions = Edition.order('release_date').to_a
    card_editions = self.editions

    avail_editions = all_editions.keep_if do |e|
      card_editions.find_index(e).nil?
    end
  end
  ##############################################################################
  def latest_edition
    return (editions.last)
  end
  ##############################################################################
  def available_count
    return (self.count - self.used_count)
  end
  ##############################################################################
  def used_count
    count = 0

    card_in_deck.each do |cid|
      count += cid.main_copies
      count += cid.side_copies
    end

    return count
  end
  ##############################################################################
  def color
    color = ''

    color += COLORS[:red][:code]   if is_red?
    color += COLORS[:green][:code] if is_green?
    color += COLORS[:blue][:code]  if is_blue?
    color += COLORS[:black][:code] if is_black?
    color += COLORS[:white][:code] if is_white?
    color =  COLORS[:colorless][:code]   if is_colorless?

    return (color)
  end
  ##############################################################################
  def is_basic_land?
    main_type == CARD_TYPES[:basic_land] || main_type == CARD_TYPES[:basic_snow_land]
  end
    ##############################################################################
  def is_land?
    main_type == CARD_TYPES[:land] || main_type == CARD_TYPES[:basic_land] || main_type == CARD_TYPES[:basic_snow_land]
  end
  ##############################################################################
  def is_red?
    !(mana_cost =~ /#{COLORS[:red][:code]}/).nil?
  end
  ##############################################################################
  def is_green?
    !(mana_cost =~ /#{COLORS[:green][:code]}/).nil?
  end
  ##############################################################################
  def is_blue?
    !(mana_cost =~ /#{COLORS[:blue][:code]}/).nil?
  end
  ##############################################################################
  def is_black?
    !(mana_cost =~ /#{COLORS[:black][:code]}/).nil?
  end
  ##############################################################################
  def is_white?
    !(mana_cost =~ /#{COLORS[:white][:code]}/).nil?
  end
  ##############################################################################
  def is_colorless?
    !(mana_cost =~ /#{COLORS[:colorless][:code]}/).nil?
  end
  ##############################################################################
  def is_none?
    !(mana_cost =~ /#{COLORS[:none][:code]}/).nil?
  end
  ##############################################################################
  def is_generic?
    !mana_cost.empty? and !is_red? and !is_green? and !is_blue? and !is_black? and !is_white? and !is_colorless? and !is_none?
  end
  ##############################################################################
  def is_multicolored?
    mcost = mana_cost.nil? ? '' : mana_cost.dup

    mcost.gsub!(/[^RGUBW]/, '')

    !mcost.empty?          and
    (mcost =~ /^R+$/).nil? and
    (mcost =~ /^G+$/).nil? and
    (mcost =~ /^U+$/).nil? and
    (mcost =~ /^B+$/).nil? and
    (mcost =~ /^W+$/).nil?
  end
  ##############################################################################
  def converted_mana_cost
    cost = nil
    mc = self.mana_cost.dup

    # Find instances of either/or colors and change to M for Multi b/c they will
    # only count as 1
    mc.gsub!(/{.\/.}/, 'M')

    if mc.sub!(/^(\d)/, '')
      cost = $1.to_i
      cost += mc.length
    elsif mc.sub!(/^X/, '')
      cost = mc.length + 1
    else
      cost = mc.length
    end

    return(cost)
  end
  ##############################################################################
  def self.sub_types
    Card.select("distinct sub_type")
      .to_a
      .delete_if {|c| c.sub_type.blank? }
      .collect! {|c| c.sub_type }
  end
  ##############################################################################
  def self.title_case(str)
    new_str = ""

    str.split(/\s+/).each do |word|
      word.downcase!
      if (word.gsub!(/-/, ' '))
        word = title_case(word)
        word.gsub!(/ /, '-')
      else
        word.capitalize! unless LOWER_WORDS.has_key?(word.to_sym)
      end

      new_str += "#{word} "
    end
    new_str.chop!

    return new_str
  end
  ##############################################################################
  def self.total(type = nil)
    sql = "select sum(count) as count from cards"
    sql += " where main_type = '#{CARD_TYPES[type]}'" unless type.nil?

    total = Card.connection.select_one(sql)
    return(total['count'])
  end
  ##############################################################################
  private

  def fixup_data
    unless (self.name.nil?)
      self.name = Card.title_case(self.name)
      self.gen_image_name
    end

    self.mana_cost.upcase! unless self.mana_cost.nil?
    self.sub_type = Card.title_case(self.sub_type) unless self.sub_type.nil?
  end

end

app/controllers/cards_controller.rb
require 'magic_cards_info'
require 'utility'

class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index

    where = []
    filter_unavailable = false
    if (params[:card].present?)
      params[:card].each do |key,value|
        next unless value.present?

        case key
        when 'name'
          where << "name like \"%#{value}%\""
        when 'color'
          if value == '*'
            where << '(mana_cost not like "%R%" and mana_cost not like "%G%" and mana_cost not like "%U%" and mana_cost not like "%B%" and mana_cost not like "%W%" and mana_cost != "" and mana_cost not like "%C%" and mana_cost not like "%-%")'
          else
            where << "mana_cost like \"%#{value}%\""
          end
        when 'text_box'
          where << "text_box like \"%#{value}%\""
        when 'sub_type'
          where << "sub_type like \"%#{value}%\""
        when 'is_available'
          filter_unavailable = value ? true : false
        else
          where << "#{key} = \"#{value}\""
        end
      end
    end

    case params[:view]
    when 'grid'
      per_page = 12
    when 'list'
      per_page = 10
    else
      per_page = params[:per]
    end

    where_str = where.join(' and ')
    @cards = Card.where(where_str)
                 .order(:name)
                 .page(params[:page])
                 .per(per_page)

    @card_count = Card.where(where_str).count
    if (filter_unavailable)
      @cards.keep_if do |card|
        # @card_count -= 1
        card.available_count > 0
      end
    end

    @total_card_count = Card.count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards, methods: [:available_count, :image_path] }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card, methods: :available_count }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    name = params[:name]
    if (name.present?)
      name = Card.title_case(name)
      @card = Card.where(:name => name).first
    end

    if @card.nil?
      @card = Card.new
      @card.count = 1
    end

    respond_to do |format|
      format.html {
        if (@card.id.present?)
          flash[:notice] = "Found Card: '#{@card.name}'"
          redirect_to :action => 'edit', :id => @card.id
        else
          if (name.present?)
            @card.name = name
            render
          else
            render :file => '/cards/new_search'
          end
        end
      }
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new()

    redirect_action = :show

    add_edition()
    @card.attributes = params[:card]

    if (@card.valid?)
      begin
        @card_data_mismatches = Utility.fetch_card_info(@card)
        redirect_action = :edit unless @card_data_mismatches.empty?
      rescue Exception => e
        case e.message
        when /card .* not found/i
          flash[:alert] = e.message
          redirect_action = :edit
        else
          flash[:alert] = "Failed to fetch card info for verification: #{e}"
        end
      end
    end

    respond_to do |format|
      if @card.save
        add_to_deck()

        format.html {
          if redirect_action == :edit
            render 'cards/edit'
          else
            redirect_to @card, notice: 'Card was successfully created.'
          end
        }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    add_edition()
    @card.attributes = params[:card]

    respond_to do |format|
      if @card.save
        add_to_deck()

        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
  ##############################################################################
  def fetch_info
    @card = Card.find(params[:id])
    @card_data_mismatches = Utility.fetch_card_info(@card)

    if (@card_data_mismatches.empty?)
      @card.save
      redirect_to @card, notice: 'Success!'
    else
      render 'cards/edit'
    end
  end
  ##############################################################################
  private

  def add_to_deck
    if (params[:deck][:deck_id].present?)
      deck = Deck.find(params[:deck][:deck_id])
      deck.add_card(@card, {:main_copies => params[:deck][:count]})
    end
  end

  def add_edition
    ed_id = params[:card].delete(:editions)
    if (ed_id.present?)
      new_ed = Edition.find(ed_id)
      @card.editions << new_ed
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper

  def rarity_to_css(card_or_rarity)
    css_class = ''

    rarity = card_or_rarity.is_a?(Card) ? card_or_rarity.rarity : card_or_rarity

    case rarity
    when 'Common'      then css_class = 'label label-inverse'
    when 'Uncommon'    then css_class = 'label label-default'
    when 'Rare'        then css_class = 'label label-warning'
    when 'Mythic Rare' then css_class = 'label label-danger'
    end

    return css_class;
  end

  def mana_cost_to_html(mana_cost)
    html = mana_cost.dup
    html.gsub!(/(X|-|\d+)/, '<span class="badge mana">\1</span>')
    html.gsub!(/R/, '<span class="badge badge-danger mana">R</span>')
    html.gsub!(/G/, '<span class="badge badge-success mana">G</span>')
    html.gsub!(/U/, '<span class="badge badge-primary mana">U</span>')
    html.gsub!(/B/, '<span class="badge badge-inverse">B</span>')
    html.gsub!(/W/, '<span class="badge badge-white mana">W</span>')
    html.gsub!(/C/, '<span class="badge mana">♢</span>')

    return html.html_safe
  end

  def card_error?(attr)
    display_error_if_error @card, attr
  end

  def card_data_mismatch?(attr)
    html = '';
    if @card_data_mismatches.present? and @card_data_mismatches.key?(attr.to_sym)
      html = "<span class='label label-info'>...#{attr.to_s.titlecase} mis-match: '#{@card_data_mismatches[attr.to_sym]}'</span>"
    end

    return html.html_safe
  end

end

app/views/cards/_card_search_form.html.erb
  <div class="form-group">
    <%= text_field :card, :name, {
      class:       "input-sm form-control",
      id:          'card_name',
      autofocus:   1, 
      placeholder: "Card Name", 
      value:       params[:card].present? ? params[:card][:name] : ''
    }%>
  </div>

  <div class="form-group">
    <%= text_field :card, :sub_type, {
      placeholder:  "Sub Type",
      class:        "typeahead input-sm form-control",
      id:           'card_sub_type',
      autocomplete: 'off', 
      value:        params[:card].present? ? params[:card][:sub_type] : '' 
    }%>
  </div>

  <div class="form-group">
    <%= text_field :card, :text_box, {
      class:       "input-sm form-control",
      id:          'card_text_box',
      placeholder: "Text Box", 
      value:       params[:card].present? ? params[:card][:text_box] : ''
    }%>
  </div> 

  <div class="form-group">
    <%= select :card, :main_type, Card::CARD_TYPES.values, {
        id:            'card_main_type',
        include_blank: 'Card Type...', 
        selected:      params[:card].present? ? params[:card][:main_type] : ''
      },
      class: "input-sm form-control"
    %>
  </div>

  <div class="form-group">
    <%= select :card, :rarity, Card::RARITIES, {
        id:            'card_rarity',
        include_blank: 'Rarity...', 
        selected:      params[:card].present? ? params[:card][:rarity] : ''
      },
      class: "input-sm form-control"
    %>
  </div>

  <div class="form-group">
    <%= select :card, :color, Card::COLORS.values.collect {|c| [c[:name], c[:code]]}, {
        id:       'card_color',
        prompt:   'Color...', 
        selected: params[:card].present? ? params[:card][:color] : ''
      },
      class: "input-sm form-control"
    %>
  </div>

app/views/cards/_form.html.erb
<%= form_for @card, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @card.errors.any? %>
    <div class="alert alert-danger">
      <h4>Unable to save Card: <%= @card.errors.count %> errors.</h4>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class=> "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, :autofocus => true, :class => 'form-control' %>
      <%= card_error? :name %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :mana_cost, :class => "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :mana_cost, :autocomplete => 'off', :class => 'form-control' %>
      <%= card_error? :mana_cost %>
      <%= card_data_mismatch? :mana_cost %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :main_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.select :main_type, Card::CARD_TYPES.values, {}, :class => 'form-control' %>
      <%= card_error? :main_type %>
      <%= card_data_mismatch? :main_type %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :sub_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :sub_type, :autocomplete => 'off', :class=> 'typeahead form-control' %>
      <%= card_error? :sub_type %>
      <%= card_data_mismatch? :sub_type %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :editions, :class => "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <ul class="list-inline">
        <% @card.editions.each do |e| %>
          <li><span class="label label-inverse"><%= e.name %></span></li>
        <% end %>
      </ul>
      <%= f.collection_select :editions, @card.available_editions.reverse, :id, :name, {:include_blank => true}, :class => 'form-control' %>
      <%= card_error? :editions %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :foil, :class => "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.check_box :foil %>
      <%= card_error? :foil %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :rarity, :class => "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <% Card::RARITIES.each do |r| %>
        <%= f.radio_button :rarity,  r, :class => 'radio-inline' %> <span class="<%= rarity_to_css(r) %>"><%= r %></span>
      <% end %>
      <%= card_error? :rarity %>
      <%= card_data_mismatch? :rarity %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :count, :class => "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <div class="input-group">
        <span class="input-group-btn">
          <button id="card_count_dec" class="btn btn-default btn-sm" type="button"><i class="glyphicon glyphicon-minus"></i></button>
        </span>
        <%= f.number_field :count, :class => "input-sm form-control", :disabled => false %>
        <span class="input-group-btn">
        <button id="card_count_inc" class="btn btn-default btn-sm" type="button"><i class="glyphicon glyphicon-plus"></i></button>
        </span>
      </div>
      <%= card_error? :count %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :deck, :class => "col-sm-2 control-label" %>
    <div class="col-sm-3">
      <%= collection_select :deck, :deck_id, Deck.order(:name).all, :id, :name, {:include_blank => true}, :class => 'form-control' %>
    </div>
    <div class="col-sm-1">
      <%= text_field :deck, :count, :class => 'input-sm form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
      <%= f.submit nil, :class => "btn btn-primary" %>
      <%= link_to 'Back', :back, :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/cards/_grid_view.html.erb
<div class="row">
  <% @cards.each do |card| %>
    <div class="col-xs-4 col-md-3 col-lg-3">
      <div class="thumbnail">
        <a href="<%= card_path(card) %>"><img src="<%= card_image_path(card) %>" class="img-responsive"></a>
      </div>
    </div>
  <% end %>
</div>

app/views/cards/_list_view.html.erb
<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Mana Cost</th>
    <th>Main Type</th>
    <th>Sub Type</th>
    <th>Rarity</th>
    <th>Count</th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td>
      <a rel="popover" href="<%= card_path card%>"
         data-placement="right"
         data-html="true"
         data-animation="false"
         data-trigger="hover"
         data-content="<img src='<%= card_image_path(card) %>' class='img-responsive'>"><%= card.name %></a>
    </td>
    <td><%= card.mana_cost %></td>
    <td><%= card.main_type %></td>
    <td><%= card.sub_type %></td>
    <td><%= card.rarity %></td>
    <td><%= card.count %></td>
    
    <td>
      <%= link_to card, :class => 'btn btn-default btn-sm' do %>
        <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
      
      <%= link_to  edit_card_path(card), :class => 'btn btn-default btn-sm' do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
      
      <%= link_to card, :class => 'btn btn-sm btn-danger', method: :delete, data: { 
        confirm: "'#{card.name}' is used in #{card.decks.count} decks.\n\nDelete?" } do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/cards/edit.html.erb
<div class="page-header"><h1>Edit Card</h1></div>

<%= render 'form' %>

app/views/cards/index.html.erb
<div class="page-header">
  <h1>Cards (<%= @card_count %>/<%= @total_card_count %>)</h1>
</div>

<%= paginate @cards %>

<form class="form-inline" method="get">

  <%= render 'card_search_form' %>

  <button type="submit" name="view" value="list" class="btn btn-default btn-sm">
    <i class="glyphicon glyphicon-list"></i>
  </button>
  <button type="submit" name="view" value="grid" class="btn btn-default btn-sm">
    <i class="glyphicon glyphicon-th"></i>
  </button>
</form>

<p>
<% if params[:view] == 'grid' %>
  <%= render 'grid_view' %>
<% else %>
  <%= render 'list_view' %>
<% end %>
</p>

app/views/cards/new.html.erb
<div class="page-header"><h1>New Card</h1></div>

<%= render 'form' %>

app/views/cards/new_search.html.erb
<div class="page-header"><h1>New Card</h1></div>

<form class="form-horizontal" method="get" action="<%= new_card_path %>">
  <div class="form-group">
    <label class="col-sm-1 control-label" for="card_name">Name:</label>
    <div class="col-sm-5">
      <div class="input-group">
         <input type="text" name="name" class="form-control" autofocus>
         <i class="input-group-addon glyphicon glyphicon-search"></i>
      </div>
    </div>
  </div>  
</form>

app/views/cards/show.html.erb
<div class="row">
  <div class="col-md-4">
    <% @card.editions.each do |e|%>
      <div class="card-image" id="card-image-<%=e.code_name%>" style="display:<%= @card.latest_edition == e ? 'inherit' : 'none' %>">
        <%= image_tag card_image_path(@card,e), :class => "img-rounded" %>
      </div>
    <% end %>
    <%= button_to 'Re-fetch Info', card_fetch_info_path, method: :get, class: "btn btn-sm btn-default"%>
  </div>
  <div class="col-md-8">
    <div class="container">
      <dl>
        <dt>Name</dt>
        <dd><%= @card.name %></dd>
        
        <dt>Mana Cost</dt>
        <dd><%= mana_cost_to_html(@card.mana_cost) %></dd>
        
        <dt>Type</dt>
        <dd><%= @card.main_type %><%= raw @card.sub_type.blank? ? '' : " &mdash; #{@card.sub_type}" %></dd>
        
        <dt>Editions/Rarity</dt>
        <dd>
          <ul class="list-inline">
            <% @card.editions.each do |e| %>
              <li><span class="<%= rarity_to_css(@card) %>" onClick="BlackLotus.Card.showImage('card-image-<%= e.code_name %>')"><%= e.name %></span></li>
            <% end %>            
          </ul>
        </dd>

        <dt>Foil</dt>
        <dd><%= @card.foil ? "Yes" : "No" %></dd>
      
        <dt>Copies</dt>
        <dd><%= @card.count %> &mdash; <%= @card.available_count %> available.</dd>

        <dt>Decks</dt>
        <dd>
          <ol>
          <% @card.card_in_deck.each do |cid| %>
            <li><%= link_to cid.deck.name, cid.deck %> (<%= cid.main_copies %>/<%= cid.side_copies %>) </li>
          <% end %>
        </ol>
        </dd>

        <div class="well"><%= raw @card.text_box.present? ? @card.text_box.sub(/\n/, "<br>") : '' %></div>
      </dl>

      <%= link_to 'Edit', edit_card_path(@card), :class => "btn btn-primary" %>
      <%= link_to 'Back', :back, :class => "btn btn-default" %>
      
    </div>
  </div>
</div>