config/routes.rb
BlackLotus::Application.routes.draw do

  resources :cards
  get 'cards/:id/fetch_info' => 'cards#fetch_info', :as => :card_fetch_info

  resources :decks
  get 'decks/:id/build'       => 'decks#build',      :as => :build_deck
  post 'decks/:id/build_save' => 'decks#build_save', :as => :save_build_deck
  get 'decks/:id/print'       => 'decks#print',      :as => :deck_print

  resources :editions

  # Utility routes
  get 'utilities/(index)' => 'utilities#index', 
    :as => :utilities
  get 'utilities/export_cards' => 'utilities#export_cards', 
    :as => :utils_export_cards
  get 'utilities/sync_db' => 'utilities#sync_db', 
    :as => :utils_sync_db

  root :to => 'home#index'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  
  ##############################################################################
  attr_accessible :name, :format

  validates_presence_of :name, :format

  has_many :card_in_deck, -> {order 'main_copies asc'}, :dependent => :destroy
  has_many :cards,        -> {order :name}, :through => :card_in_deck
  ##############################################################################
  def main_count
    count = 0
    card_in_deck.each do |a|
      count += a.main_copies
    end

    return (count);
  end
  ##############################################################################
  def side_count
    count = 0
    card_in_deck.each do |a|
      count += a.side_copies
    end
  
    return (count);
  end
  ##############################################################################
  def validate
    reasons = []
    is_valid = true
    format = Format::FORMATS[self.format]

    # min cards
    unless format[:min_cards].nil?
      if self.main_count < format[:min_cards]
        is_valid = false
        reasons << {card: nil, msg: "Not enough cards in main deck (#{self.main_count})."}
      end
    end

    # max cards
    unless format[:max_cards].nil?
      if self.main_count > format[:max_cards]
        is_valid = false
        reasons << {card: nil, msg: "Too many cards in main deck (#{self.main_count})."}
      end
    end

    # sideboard size
    unless format[:sideboard_size].nil?
      if self.side_count != 0 && self.side_count != format[:sideboard_size]
        is_valid = false
        reasons << {card: nil, msg: "Sideboard does not have exactly #{format[:sideboard_size]} cards."}
      end
    end

    banned_cards = format[:banned_cards].nil? ? [] : format[:banned_cards]
    restricted_cards = format[:restricted_cards].nil? ? [] : format[:restricted_cards]

    self.card_in_deck.each do |cid|
      card = cid.card
      next if card.main_type == Card::CARD_TYPES[:basic_land]
      next if card.main_type == Card::CARD_TYPES[:basic_snow_land]

      # Max copies of each card
      if (cid.main_copies > format[:max_copies] || cid.side_copies > format[:max_copies])
        is_valid = false
        reasons << {card: card, msg: "Too many copies."}
      end

      # legal editions
      unless format[:legal_editions].nil?
        is_legal = false
        card.editions.each do |e|
          if format[:legal_editions].include?(e.name)
            is_legal = true
            break
          end
        end

        unless is_legal
          is_valid = false
          reasons << {card: card, msg: "No legal edition."}
        end
      end

      # banned cards
      if banned_cards.include?(card.name)
        is_valid = false
        reasons << {card: card, msg: "Banned."}
      end

      # restricted cards -- can only have 1 copy in deck
      if restricted_cards.include?(card.name)
        if (cid.main_copies > 1 || cid.side_copies > 1)
          is_valid = false
          reasons << {card: card, msg: "Restricted. Too many copies."}
        end
      end

    end

    return (reasons)
  end
  ##############################################################################
  def stats
    stats = {
      :main_type => {},
      :color     => {
        :red        => 0,
        :green      => 0,
        :blue       => 0,
        :black      => 0,
        :white      => 0,
        :colorless  => 0
      },
      :editions => {},
      :cost     => Array.new(7,0)
    };

    card_in_deck.each do |cid|
      next unless cid.main_copies > 0

      card = cid.card
      copies = cid.main_copies

      # Cost
      unless (card.is_land?)
        cost = card.converted_mana_cost
        cost = 6 if cost >= 6
        stats[:cost][cost] += copies
      end

      # Main Type
      if (stats[:main_type][card.main_type].nil?)
        stats[:main_type][card.main_type] = copies
      else
        stats[:main_type][card.main_type] += copies
      end

      # Editions
      unless (card.is_basic_land?)
        if (stats[:editions][card.latest_edition.name].nil?)
          stats[:editions][card.latest_edition.name] = copies
        else
          stats[:editions][card.latest_edition.name] += copies
        end
      end

      # Color
      stats[:color][:red]       += copies if card.is_red?
      stats[:color][:green]     += copies if card.is_green?
      stats[:color][:blue]      += copies if card.is_blue?
      stats[:color][:black]     += copies if card.is_black?
      stats[:color][:white]     += copies if card.is_white?
      stats[:color][:colorless] += copies if card.is_colorless?

    end

    return (stats)
  end
  ##############################################################################
  def add_card(card, options = {:main_copies => 1, :side_copies => 0})
    card_in_deck = CardInDeck.new(
      :deck => self,
      :card => card,
      :main_copies => options[:main_copies],
      :side_copies => options[:side_copies] || 0
    )

    card_in_deck.save!
  end
  ##############################################################################
  def remove_card(card)

    # ideally this should work, but isn't
    # self.cards.destroy(card)
    # or this
    # self.card_in_deck.destroy(card)

    index = self.card_in_deck.find_index do |cid|
      cid.card.id == card.id
    end

    card_in_deck = self.card_in_deck[index]
    raise "Failed to destroy #{card_in_deck.inspect}" unless card_in_deck.destroy
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.where("name like '%#{params[:search_string]}%'")
                  .order(:name)
                  .page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decks }
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    @deck = Deck.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @deck }
    end
  end

  def print
    @deck = Deck.find(params[:id])

    respond_to do |format|
      format.html {
        render :layout => false
      }
    end
  end

  # GET /decks/new
  # GET /decks/new.json
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = Deck.find(params[:id])
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(params[:deck])

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render json: @deck, status: :created, location: @deck }
      else
        format.html { render action: "new" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.json
  def update
    @deck = Deck.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  def build
    @deck = Deck.find(params[:id])
  end

  def build_save
    deck = Deck.find(params[:id])

    add_count = 0
    rm_count  = 0

    params.each do |key, card_data|
      case key
      when (/^add_card_/)
        parts = card_data.split('|')

        copy_opts = {
          :main_copies => 0,
          :side_copies => 0
        };

        case parts[1]
        when 'main' 
          copy_opts[:main_copies]  = parts[2]
        when 'side'
          copy_opts[:side_copies]  = parts[2]
        end

        card = Card.find(parts[0])
        deck.add_card(card, copy_opts)
        add_count+=1
      when (/^remove_card_/)
        card = Card.find(card_data)
        deck.remove_card(card)
        rm_count+=1
      end
    end

    redirect_to build_deck_path, 
      :notice => "Deck successfully updated. Added [#{add_count}] cards. Removed [#{rm_count}] cards."
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/decks_helper.rb
module DecksHelper

  def color_to_label(color)
    label = case color
    when :red
      'label label-danger'
    when :green
      'label label-success'
    when :blue
      'label label-primary'
    when :black
      'label label-inverse'
    when :white
      'label label-warning'
    else
      'label label-default'
    end

    return(label)
  end

  def deck_error?(attr)
    return @deck.errors[attr].present?
  end

  def display_deck_error(attr)
    display_error_if_error @deck, attr
  end
  
end

app/views/decks/_form.html.erb
<%= form_for @deck, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @deck.errors.any? %>
    <div class="alert alert-danger">
      <h4>Unable to save Deck: <%= @deck.errors.count %> errors.</h4>
    </div>
  <% end %>

  <div class="form-group <%= deck_error?(:name) ? 'has-error' : '' %>">
    <%= f.label :name, :class=> "col-sm-1 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, :autofocus => true, :class => 'form-control' %>
      <%= display_deck_error :name %>
    </div>
  </div>

  <div class="form-group <%= deck_error?(:format) ? 'has-error' : '' %>">
    <%= f.label :format, :class => "col-sm-1 control-label" %>
    <div class="col-sm-5">
      <%= f.select :format, Format::FORMATS.keys.collect {|n| [n,n] }, {}, :class => 'form-control' %>
      <%= display_deck_error :format %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-5">
      <%= f.submit nil, :class => "btn btn-primary" %>
      <% unless @deck.id.nil? %>
        <%= link_to 'Builder', build_deck_path(@deck), :class => "btn btn-default"  %>
      <% end %>
      <%= link_to 'Back', :back, :class => "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/decks/_stats.html.erb
<% stats = @deck.stats %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title text-center">Color</div>
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <% [:red, :green, :blue, :black, :white, :colorless].each do |color| %>
        <% count = stats[:color][color] %>
        <li class="list-group-item">
          <span class="badge"><%= count %></span>
          <div class="deck-view-filter <%= color_to_label(color) %>" onClick="BlackLotus.DeckView.highlightColor('<%= color %>')"><%= color.capitalize %></div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title text-center">Type</div>
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <% stats[:main_type].sort.each do |mt| %>
        <li class="list-group-item"> 
          <span class="badge"><%= mt[1] %></span>
          <span class="deck-view-filter label label-white" onClick="BlackLotus.DeckView.highlightMainType('<%= mt[0] %>')"><%= mt[0] %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title text-center">Editions</div>
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <% stats[:editions].sort.each do |e| %>
        <li class="list-group-item">
          <span class="badge"><%= e[1] %></span>
          <span class="deck-view-filter label label-white" onClick='BlackLotus.DeckView.highlightEdition("<%= e[0] %>")'><%= e[0] %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title text-center">Mana Distribution</div>
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <% cost = 0 %>
      <% stats[:cost].each do |count| %>
        <li class="list-group-item">
          <span class="badge"><%= cost %><%= cost >= 6 ? '+' : '' %></span>
          <div class="progress">
            <div class="progress-bar progress-bar-info" style="width: <%= (count.to_f / @deck.main_count) * 100 %>%">
              <%= count > 0 ? count : '' %>
            </div>
          </div>
        </li>
      <% cost = cost + 1 %>
      <% end %>
    </ul>
  </div>
</div>

app/views/decks/_validation.html.erb
<% reasons = @deck.validate %>
<% unless reasons.empty? %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title text-center">Deck Validation</div>
  </div>
  <div class="panel-body">
  <% if reasons.present? %>
      <ul class="list-group">
      <% reasons.each do |r|%>
        <li class="alert alert-danger list-group-item">
          <small><%= r[:card].nil? ? '' : link_to("#{r[:card].name}:", card_path(r[:card])) %> <%= r[:msg]%></small>
        </li>
      <% end %>
      </ul>
  <% end %>
  </div>
</div>

<% end %>

app/views/decks/build.html.erb
<div class="page-header">
  <h1>Deck Builder:  <%= @deck.name %> &mdash; <%= @deck.format %></h1>
</div>

<div class="container">

  <div class="row">
    <form class="form-inline" id="search_form" onSubmit="BlackLotus.Deckbuilder.card_search(1);return false;">
      <%= render 'cards/card_search_form' %>
      <button type="submit" id="search_button" name="search" class="btn btn-default btn-sm">
        <i class="glyphicon glyphicon-search"></i>
      </button>
      <button type="reset" id="search_button" name="reset" class="btn btn-default btn-sm">
        <i class="glyphicon glyphicon-remove"></i>
      </button>
    </form>
  </div>

  <p></p>

  <div class="row">
    <div class="col-md-1">
      <button type="button" name="prev" class="btn btn-default btn-sm" onClick="BlackLotus.Deckbuilder.card_search_prev()">
        <i class="glyphicon glyphicon-arrow-left"></i>
      </button>
    </div>
    <div class="col-md-10" id="search_results"></div>
    <div class="col-md-1">
      <button type="button" name="next" class="btn btn-default btn-sm" onClick="BlackLotus.Deckbuilder.card_search_next()">
        <i class="glyphicon glyphicon-arrow-right"></i>
      </button>
    </div>
  </div>

  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <button type="button" class="btn btn-block" data-toggle="collapse" data-target="#main"><i class="glyphicon glyphicon-eye-open"></i> Main Deck (<%= @deck.main_count %>)</button>
      </div>
      <div id="main" class="panel-body collapse in">
        <% @deck.card_in_deck.each do |cid| %>
        <% next unless cid.main_copies > 0 %>
        <% card = cid.card %>
        <div id="card_<%= card.id %>" data-id="<%= card.id %>" class="col-md-3 existing_card">
          <div id="card_img_<%= card.id %>" class="thumbnail">
            <img src="<%= card_image_path(card) %>" class="img-responsive">
            <div class="caption text-center">
              x <strong><%= cid.main_copies %></strong>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <button type="button" class="btn btn-block" data-toggle="collapse" data-target="#side"><i class="glyphicon glyphicon-eye-open"></i> Sideboard (<%= @deck.side_count %>)</button>
      </div>
      <div id="side" class="panel-body collapse in">
        <% @deck.card_in_deck.each do |cid| %>
        <% next unless cid.side_copies > 0 %>
        <% card = cid.card %>
        <div id="card_<%= card.id %>" data-id="<%= card.id %>" class="col-md-3 existing_card">
          <div id="card_img_<%= card.id %>" class="thumbnail">
            <img src="<%= card_image_path(card) %>" class="img-responsive">
            <div class="caption text-center">
              x <strong><%= cid.side_copies %></strong>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

<!-- ####################################################################### -->

<% content_for :sidebar do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <form class="col-md-12" id="deck_builder_form" method="post" action="<%= save_build_deck_path %>">
        <div id="cards_to_add"></div>
        <div id="cards_to_remove"></div>
        <button class="btn btn-primary">Save</button>
        <%= link_to "Done", @deck, :class => "btn btn-default btn-sm" %>
      </form>
    </div>
  </div>

  <%= render 'validation' %>
  <%= render 'stats' %>
<% end %>

<% content_for :javascript do %>
<script type="text/javascript">
  BlackLotus.Deckbuilder.init();
</script>
<% end %>

app/views/decks/edit.html.erb
<div class="page-header"><h1>Edit Deck</h1></div>

<%= render 'form' %>

app/views/decks/index.html.erb
<div class="page-header"><h1>Decks</h1></div>

<%= paginate @decks %>

<form role="form">
  <div class="form-group">
    <div class="input-group">
      <input type="text" name="search_string" class="form-control" autofocus>
      <i class="input-group-addon glyphicon glyphicon-search"></i>
    </div>
  </div>
</form>

<p></p>

<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Format</th>
    <th>Card Count</th>
    <th></th>
  </tr>

<% @decks.each do |deck| %>
  <tr class="<%= deck.validate.empty? ? '' : 'danger' %>">
    <td><%= link_to deck.name, deck %></td>
    <td><%= deck.format %></td>
    
    <td><span class="badge"><%= deck.main_count %></span></td>
    
    <td>
      <div class="pull-right">
      <%= link_to deck, :class => "btn btn-default btn-sm" do %>
        <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
      <%= link_to edit_deck_path(deck), :class => "btn btn-default btn-sm" do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
      <%= link_to deck, method: :delete, :class => "btn btn-sm btn-danger", data: { confirm: "Delete '#{deck.name}'?" } do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    </div>
    </td>
  </tr>
<% end %>
</table>

app/views/decks/new.html.erb
<div class="page-header"><h1>New Deck</h1></div>

<%= render 'form' %>

app/views/decks/print.html.erb
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style type="text/css">
    <!--
      body, html, img, a {margin: 0; padding: 0; border: none;}
    -->
    </style>
  </head>

  <body>
  <% @deck.cards.each do |card| %>
    <img width="222" height="319" style="margin: 0 1px 1px 0;" src="<%= card_image_path(card) %>">
  <% end %>
  </body>

</html>

app/views/decks/show.html.erb
<div class="page-header">
  <h1><%= @deck.name %> &mdash; <%= @deck.format %> (<%= @deck.main_count %>/<%= @deck.side_count %>)</h1>
  <%= link_to 'Edit', edit_deck_path(@deck), :class => "btn btn-primary btn-xs" %>
  <%= link_to 'Builder', build_deck_path(@deck), :class => "btn btn-success btn-xs" %>
  <%= link_to 'Print', deck_print_path(@deck), :class => "btn btn-warning btn-xs" %>
  <%= link_to 'Back', :back, :class => "btn btn-default btn-xs" %>
</div>

<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-center">Main Deck (<%= @deck.main_count %>)</h3>
      </div>
      <div class="panel-body">
        <% @deck.card_in_deck.each do |card_in_deck| %>
          <% next unless card_in_deck.main_copies > 0 %>
          <div id="main_card_<%= card_in_deck.card.id %>" 
               class="col-xs-4 col-md-3 col-lg-3" 
               data-type="card" 
               data-edition="<%= card_in_deck.card.latest_edition.name %>" 
               data-color="<%= card_in_deck.card.color %>"
               data-main-type="<%= card_in_deck.card.main_type %>">
            <div class="thumbnail">
              <a href="<%= card_path card_in_deck.card %>"><img src="<%= card_image_path(card_in_deck.card) %>" class="img-responsive"></a>
              <div class="caption text-center">
                x <strong><%= card_in_deck.main_copies %></strong>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-center">Sideboard (<%= @deck.side_count %>)</h3>
      </div>
      <div class="panel-body">
        <% @deck.card_in_deck.each do |card_in_deck| %>
          <% next unless card_in_deck.side_copies > 0 %>
          <div id="side_card_<%= card_in_deck.card.id %>"
               class="col-xs-4 col-md-3 col-lg-3"
               data-type="card" 
               data-edition="<%= card_in_deck.card.latest_edition.name %>" 
               data-color="<%= card_in_deck.card.color %>"
               data-main-type="<%= card_in_deck.card.main_type %>">
            <div class="thumbnail">
              <a href="<%= card_path card_in_deck.card %>"><img src="<%= card_image_path(card_in_deck.card) %>" class="img-responsive"></a>
              <div class="caption text-center">
                x <strong><%= card_in_deck.side_copies %></strong>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar do %>
<!-- <div class="well well-sm"> -->
  <%= render 'validation' %>
  <%= render 'stats' %>
<!-- </div> -->
<% end %>