config/routes.rb
BlackLotus::Application.routes.draw do

  resources :cards
  get 'cards/:id/fetch_info' => 'cards#fetch_info', :as => :card_fetch_info

  resources :decks
  get 'decks/:id/build'       => 'decks#build',      :as => :build_deck
  post 'decks/:id/build_save' => 'decks#build_save', :as => :save_build_deck
  get 'decks/:id/print'       => 'decks#print',      :as => :deck_print

  resources :editions

  # Utility routes
  get 'utilities/(index)' => 'utilities#index', 
    :as => :utilities
  get 'utilities/export_cards' => 'utilities#export_cards', 
    :as => :utils_export_cards
  get 'utilities/sync_db' => 'utilities#sync_db', 
    :as => :utils_sync_db

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BlackLotus" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse">
          <span class="glyphicon glyphicon-bar"></span>
          <span class="glyphicon glyphicon-bar"></span>
          <span class="glyphicon glyphicon-bar"></span>
        </button>
        <span class="navbar-brand"><abbr title="{T}, Sacrifice Black Lotus: Add three mana of any one color to your mana pool.">BlackLotus</abbr></span>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= menu_item_active?('home') %>"><%= link_to "Home", root_path  %></li>
          <li class="<%= menu_item_active?('cards') %>"><%= link_to "Cards", cards_path  %></li>
          <li class="<%= menu_item_active?('decks') %>"><%= link_to "Decks", decks_path  %></li>
          <li class="<%= menu_item_active?('editions') %>"><%= link_to "Editions", editions_path  %></li>
        </ul>
      </div>
    </nav>

    <!-- <div class="container"> -->
      <div class="row">
        <div class="col-md-3">
          <div class="container">
            <% if Rails.env == 'development' %>
              <p><%= image_tag 'http://placehold.it/250x200/888888/000000&text=Bl', :class => 'img-rounded img-responsive', :alt => 'Bl Development'%></p>
            <% else %>
              <p><%= image_tag "black_lotus.jpg", :class => 'img-rounded img-responsive'%></p>
            <% end %>
            <ul class="nav nav-pills nav-stacked">
              <li><%= link_to "Add Card", new_card_path %></li>
              <li><%= link_to "Add Deck", new_deck_path %></li>
              <li><%= link_to "Utilities", utilities_path %></li>
            </ul>
          </div>
          <hr>
          <div class="container">
            <%= yield(:sidebar) %>
          </div>
        </div>
        <div class="col-md-9">
          <div class="container">
          <% flash.each do |type, message| %>
            <div class="alert <%= flash_class(type) %> alert-dismissable">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>          
          <%= yield %>
          </div>
        </div>
      </div>

      <p></p>

      <footer>
        <p class="muted well well-small text-center">&copy; Craig N. Caroon 2013-2015</p>
      </footer>

    <!-- </div> -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield(:javascript) %>

  </body>
</html>